services:
  - type: web
    name: attendance-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn attendance_app.wsgi:application --workers=3 --timeout=90 --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: CSRF_TRUSTED_ORIGINS
        value: https://*.onrender.com
    autoDeploy: true
    plan: free
    healthCheckPath: /

databases:
  - name: attendance-db
    plan: free

